name: Deploy to EC2 dengan Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH via Pem Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Jalankan SSH dan Build Docker di dalam EC2
        run: |
          # Melakukan koneksi ke EC2 secara automatis lalu mengeksekusi script
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          
          # 1. Pindah ke folder projek yang sudah di-clone
          cd ~/trashbin
          
          # 2. Tarik update terbaru dari Github
          git pull origin main
          
          # 3. Matikan kontainer lama jika ada, lalu rangkai (build) ulang dan hidupkan yang baru
          sudo docker compose down
          sudo docker compose up -d --build
          
          EOF
